### PR TITLE
Update setup.py

### PR DESCRIPTION
**Pull request by uvilla**
Resolve issue #71 .

### CODE REVIEW

**Comment by nschloe** [comment]
This will break on compilers that don't have a C++14 flag. Also, we don't need 14, just 11.

**Comment by uvilla** [comment]
@nschloe,

Please see [here](https://github.com/nschloe/pygalmesh/pull/76/checks?check_run_id=586066420).

Recent versions of CGAL require __at least__ the `c++14` standard.

As you can see from the logfile, the CGAL header `CGAL/Kernel/hash_functions.h` uses `std::enable_if_t`, which is a c++14 feature (see https://en.cppreference.com/w/cpp/types/enable_if).

Would you be open to a PR where I set:

```
extra_compile_args = [os.environ.get("PYGALMESH_EXTRA_COMPILE_FLAGS", "") ]
```

This will give users a hook to successfully compile on older compilers which don't use `c++14` as default.

**Comment by nschloe** [comment]
Can't you use `CFLAGS` to do just that?

**Comment by nschloe** [comment]
As for adding compiler flags, it should probably look more like this: https://github.com/pybind/python_example/blob/master/setup.py

**Comment by uvilla** [comment]
What is the difference between the builts on `Github actions` and `circleci`?

I'm not sure why the built on `Github action` fails?

**Comment by nschloe** [comment]
Forget about the gh-actions, they aren't required anyway.

**Comment by nschloe** [comment]
Why c++17 now? This fails on compilers which don't have that yet.

**Comment by uvilla** [comment]
`c++17` was a trial and error attempt to solve the compilation issue in the `Github action`, sorry about that.

To conclude the discussion.

```
export CFLAGS=-std=c++14
pip install pygalmesh
```

Works fine without having to modify the `setup.py`.

I suggest we decline this PR, and add a note in the `README.md` about setting that flag as an environment variable.

**Comment by nschloe** [comment]
I wouldn't be against adding `-std=c++14` either, if that makes things easier for some people. I'm not sure how many people experience compiler issues then because their compiler doesn't support it. Probably few.

**Comment by uvilla** [comment]
Thank you @nschloe .

Adding this flag may be useful to many MacOS users. Even the latest MacOs comes with a old compiler.

**Comment by nschloe** [comment]
Let's try it.

**Pull request merged**
